package handler

const (
	STATUS_OK             = `OK`
	STATUS_NOTFOUND       = `NOT FOUND`
	STATUS_BADREQUEST     = `BAD REQUEST`
	STATUS_INVALIDPAYLOAD = `ERROR VALIDATE FIELD`
	STATUS_SERVERERROR    = `SERVER ERROR`
)
